--
-- Instrucciones para DBeaver (local)
-- 1) Crea la base de datos 'duit_local' en tu servidor local.
-- 2) Abre un editor SQL conectado a 'duit_local'.
-- 3) Pega y ejecuta este script.
--
-- public.address definition

-- Drop table

-- DROP TABLE public.address;

CREATE TABLE public.address (
	id_address int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	created_by varchar(100) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(100) NULL,
	street_address varchar(200) NOT NULL,
	city varchar(100) NOT NULL,
	country varchar(50) NOT NULL,
	postal_code varchar(5) NULL,
	province varchar(100) NOT NULL,
	CONSTRAINT address_pkey PRIMARY KEY (id_address)
);
CREATE INDEX idx_address_city ON public.address USING btree (city);
CREATE INDEX idx_address_full_location ON public.address USING btree (city, postal_code, province);
CREATE INDEX idx_address_location ON public.address USING btree (city, province);
CREATE INDEX idx_address_postal ON public.address USING btree (postal_code);
CREATE INDEX idx_address_province ON public.address USING btree (province);


-- public.category definition

-- Drop table

-- DROP TABLE public.category;

CREATE TABLE public.category (
	id_category int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	created_by varchar(100) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(100) NULL,
	active bool NOT NULL,
	description varchar(200) NULL,
	"name" varchar(100) NOT NULL,
	CONSTRAINT category_pkey PRIMARY KEY (id_category),
	CONSTRAINT uk46ccwnsi9409t36lurvtyljak UNIQUE (name)
);
CREATE INDEX idx_category_active ON public.category USING btree (active);
CREATE INDEX idx_category_name ON public.category USING btree (name);


-- public.user_role definition

-- Drop table

-- DROP TABLE public.user_role;

CREATE TABLE public.user_role (
	id_role int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	created_by varchar(100) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(100) NULL,
	active bool NOT NULL,
	description varchar(100) NULL,
	"name" varchar(20) NOT NULL,
	CONSTRAINT uklnth8w122wgy7grrjlu8hjmuu UNIQUE (name),
	CONSTRAINT user_role_name_check CHECK (((name)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying, 'PROFESSIONAL'::character varying, 'MODERATOR'::character varying])::text[]))),
	CONSTRAINT user_role_pkey PRIMARY KEY (id_role)
);
CREATE INDEX idx_role_active ON public.user_role USING btree (active);
CREATE INDEX idx_role_name ON public.user_role USING btree (name);


-- public.app_user definition

-- Drop table

-- DROP TABLE public.app_user;

CREATE TABLE public.app_user (
	id_user int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	created_by varchar(100) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(100) NULL,
	active bool NOT NULL,
	dni varchar(9) NULL,
	first_name varchar(100) NOT NULL,
	last_login_at timestamp(6) NULL,
	last_name varchar(150) NOT NULL,
	"password" varchar(255) NOT NULL,
	phone varchar(20) NULL,
	registered_at timestamp(6) NULL,
	username varchar(100) NOT NULL,
	id_address int8 NULL,
	id_role int8 NOT NULL,
	CONSTRAINT app_user_pkey PRIMARY KEY (id_user),
	CONSTRAINT uk3k4cplvh82srueuttfkwnylq0 UNIQUE (username),
	CONSTRAINT ukgx20egnrk8nk5kxk7sl1wuu32 UNIQUE (dni),
	CONSTRAINT fk14dtygempgyaywb2m7dqt91ah FOREIGN KEY (id_address) REFERENCES public.address(id_address),
	CONSTRAINT fk38twpvotwrmn48niqowojuod7 FOREIGN KEY (id_role) REFERENCES public.user_role(id_role)
);
CREATE INDEX idx_user_active ON public.app_user USING btree (active);
CREATE INDEX idx_user_dni ON public.app_user USING btree (dni);
CREATE INDEX idx_user_role ON public.app_user USING btree (id_role);
CREATE INDEX idx_user_username ON public.app_user USING btree (username);


-- public.professional_profile definition

-- Drop table

-- DROP TABLE public.professional_profile;

CREATE TABLE public.professional_profile (
	id_professional int8 NOT NULL,
	created_at timestamp(6) NULL,
	created_by varchar(100) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(100) NULL,
	description text NOT NULL,
	hourly_rate numeric(8, 2) NOT NULL,
	nif varchar(9) NOT NULL,
	registered_at timestamp(6) NULL,
	CONSTRAINT professional_profile_pkey PRIMARY KEY (id_professional),
	CONSTRAINT uk3ga8mgx9obrnhlsixka9lvt6y UNIQUE (nif),
	CONSTRAINT fk4qn09rsbkv6nsu7ka2f3vjuj3 FOREIGN KEY (id_professional) REFERENCES public.app_user(id_user)
);
CREATE INDEX idx_professional_hourly_rate ON public.professional_profile USING btree (hourly_rate);
CREATE INDEX idx_professional_nif ON public.professional_profile USING btree (nif);


-- public.service_request definition

-- Drop table

-- DROP TABLE public.service_request;

CREATE TABLE public.service_request (
	id_request int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	created_by varchar(100) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(100) NULL,
	deadline timestamp(6) NULL,
	description text NOT NULL,
	requested_at timestamp(6) NULL,
	status varchar(20) NOT NULL,
	title varchar(150) NOT NULL,
	id_category int8 NOT NULL,
	id_client int8 NOT NULL,
	id_service_address int8 NULL,
	CONSTRAINT service_request_pkey PRIMARY KEY (id_request),
	CONSTRAINT service_request_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying])::text[]))),
	CONSTRAINT fkbacj8l7fl6r8ye6v3gkns2kbr FOREIGN KEY (id_client) REFERENCES public.app_user(id_user),
	CONSTRAINT fkegg2fa41f5sh2s6g2b3ul2jjm FOREIGN KEY (id_category) REFERENCES public.category(id_category),
	CONSTRAINT fkgpse7o8e1h9ph5sc0klll3udg FOREIGN KEY (id_service_address) REFERENCES public.address(id_address)
);
CREATE INDEX idx_request_category ON public.service_request USING btree (id_category);
CREATE INDEX idx_request_client ON public.service_request USING btree (id_client);
CREATE INDEX idx_request_service_address ON public.service_request USING btree (id_service_address);
CREATE INDEX idx_request_status ON public.service_request USING btree (status);


-- public.access_log definition

-- Drop table

-- DROP TABLE public.access_log;

CREATE TABLE public.access_log (
	id_log int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	accessed_at timestamp(6) NULL,
	source_ip varchar(45) NULL,
	success bool DEFAULT false NOT NULL,
	id_user int8 NOT NULL,
	CONSTRAINT access_log_pkey PRIMARY KEY (id_log),
	CONSTRAINT fk7j87wpwt1pofxtufkm4wc5til FOREIGN KEY (id_user) REFERENCES public.app_user(id_user)
);
CREATE INDEX idx_access_log_accessed_at ON public.access_log USING btree (accessed_at);
CREATE INDEX idx_access_log_user ON public.access_log USING btree (id_user);


-- public.job_application definition

-- Drop table

-- DROP TABLE public.job_application;

CREATE TABLE public.job_application (
	id_application int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	created_by varchar(100) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(100) NULL,
	applied_at timestamp(6) NULL,
	message text NULL,
	proposed_price numeric(8, 2) NULL,
	responded_at timestamp(6) NULL,
	status varchar(255) NOT NULL,
	id_professional int8 NOT NULL,
	id_request int8 NOT NULL,
	CONSTRAINT job_application_pkey PRIMARY KEY (id_application),
	CONSTRAINT job_application_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying, 'WITHDRAWN'::character varying])::text[]))),
	CONSTRAINT fk8l1jdfhge2l9b0joc6e2qatrr FOREIGN KEY (id_request) REFERENCES public.service_request(id_request),
	CONSTRAINT fkei97ags40gccfwmeom06urdk6 FOREIGN KEY (id_professional) REFERENCES public.professional_profile(id_professional)
);
CREATE INDEX idx_application_applied_at ON public.job_application USING btree (applied_at);
CREATE INDEX idx_application_professional ON public.job_application USING btree (id_professional);
CREATE INDEX idx_application_request ON public.job_application USING btree (id_request);
CREATE INDEX idx_application_status ON public.job_application USING btree (status);


-- public.professional_category definition

-- Drop table

-- DROP TABLE public.professional_category;

CREATE TABLE public.professional_category (
	id_professional int8 NOT NULL,
	id_category int8 NOT NULL,
	CONSTRAINT professional_category_pkey PRIMARY KEY (id_professional, id_category),
	CONSTRAINT fk44cniwn8q38xkb1q03uu38wpo FOREIGN KEY (id_category) REFERENCES public.category(id_category),
	CONSTRAINT fkdvn997ug4aljj2kfnhbvubeky FOREIGN KEY (id_professional) REFERENCES public.professional_profile(id_professional)
);


-- public.service_job definition

-- Drop table

-- DROP TABLE public.service_job;

CREATE TABLE public.service_job (
	id_job int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	created_by varchar(100) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(100) NULL,
	agreed_price numeric(8, 2) NOT NULL,
	end_date timestamp(6) NULL,
	notes text NULL,
	start_date timestamp(6) NULL,
	status varchar(255) NOT NULL,
	id_application int8 NOT NULL,
	id_request int8 NOT NULL,
	CONSTRAINT service_job_pkey PRIMARY KEY (id_job),
	CONSTRAINT service_job_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'PAUSED'::character varying])::text[]))),
	CONSTRAINT fk7fvy10aimxcx6y5rv7pg8l6qd FOREIGN KEY (id_application) REFERENCES public.job_application(id_application),
	CONSTRAINT fkcm382f1y8ga1hksbuem1f53c9 FOREIGN KEY (id_request) REFERENCES public.service_request(id_request)
);
CREATE INDEX idx_job_active ON public.service_job USING btree (status, start_date);
CREATE INDEX idx_job_application ON public.service_job USING btree (id_application);
CREATE INDEX idx_job_dates ON public.service_job USING btree (start_date, end_date);
CREATE INDEX idx_job_price ON public.service_job USING btree (agreed_price);
CREATE INDEX idx_job_request ON public.service_job USING btree (id_request);
CREATE INDEX idx_job_status ON public.service_job USING btree (status);


-- public.rating definition

-- Drop table

-- DROP TABLE public.rating;

CREATE TABLE public.rating (
	id_rating int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	created_by varchar(100) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(100) NULL,
	"comment" varchar(500) NULL,
	rated_at timestamp(6) NULL,
	score int4 NOT NULL,
	status varchar(255) NOT NULL,
	"type" varchar(30) NOT NULL,
	id_job int8 NOT NULL,
	CONSTRAINT rating_pkey PRIMARY KEY (id_rating),
	CONSTRAINT rating_score_check CHECK (((score >= 1) AND (score <= 5))),
	CONSTRAINT rating_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PUBLISHED'::character varying, 'HIDDEN'::character varying])::text[]))),
	CONSTRAINT rating_type_check CHECK (((type)::text = ANY ((ARRAY['CLIENT_TO_PROFESSIONAL'::character varying, 'PROFESSIONAL_TO_CLIENT'::character varying])::text[]))),
	CONSTRAINT fk1hdpi12ab5kxl0443r8u1c78p FOREIGN KEY (id_job) REFERENCES public.service_job(id_job)
);
CREATE INDEX idx_rating_job ON public.rating USING btree (id_job);
CREATE INDEX idx_rating_type ON public.rating USING btree (type);