spring.application.name=Duit
server.port=8080
spring.thymeleaf.cache=false



logging.level.root=ERROR
logging.level.org.thymeleaf=TRACE
logging.level.org.springframework.web=ERROR


# Datasource MySQL (Railway)
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Ejecutar data.sql
spring.sql.init.mode=always
spring.sql.init.platform=mysql


